Koios/Models/Country.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Koios.Models
{
	public class Country
	{
		[Key]
		public int CountryId { get; set; }
		public string CountryName { get; set; }
		public ICollection<Town> Town { get; set; }
	}
}

Koios/Models/DTOs/CountryDto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Koios.Models
{
	public class CountryDto
	{
		public int CountryId { get; set; }
		public string CountryName { get; set; }
		public ICollection<TownDto> Towns { get; set; }
	}
}

Koios/Models/DTOs/TownDto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Koios.Models
{
	public class TownDto
	{
		public int TownId { get; set; }
		public string TownName { get; set; }
		// Ne znam koliko koja država ima znakova, pa sam limitirao na 10
		public string PostalCode { get; set; }
		public int CountryId { get; set; }
		public Country Countries { get; set; }
	}
}

Koios/Models/Side Classes/AutoMapping.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;

namespace Koios.Models.Side_Classes
{
	public class AutoMapping : Profile
	{
		public AutoMapping()
		{
			CreateMap<Town, TownDto>();
			CreateMap<Country, CountryDto>();
			CreateMap<TownDto, Town>();
			CreateMap<CountryDto, Country>();
		}
	}
}

Koios/Models/Side Classes/ErrorViewModel.cs
using System;

namespace Koios.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Koios/Models/Town.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Koios.Models
{
	public class Town
	{
		[Key]
		public int TownId { get; set; }
		[Required(ErrorMessage = "Ime grada je obavezno!")]
		[MaxLength(80)]
		[DataType(DataType.Text)]
		public string TownName { get; set; }
		[Required(ErrorMessage = "Poštanski broj je obavezan!")]
		[MaxLength(10)]
		// Ne znam koliko koja država ima znakova, pa sam limitirao na 10
		public string PostalCode { get; set; }
		[Required(ErrorMessage = "Odabir grada je obavezan!")]
		public int CountryId { get; set; }
		public Country Countries { get; set; }

	}
}

Koios/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Koios.Models;

namespace Koios.Controllers
{
	public class HomeController : Controller
	{

		public HomeController()
		{
		}

		public IActionResult Index()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Koios/Controllers/TownsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Koios.Models;
using AutoMapper;
using Koios.Interfaces;
using System.Threading.Tasks.Dataflow;
using Microsoft.VisualStudio.Web.CodeGeneration;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace Koios.Controllers
{
	public class TownsController : Controller
	{
		private readonly IServiceTown _serviceTown;

		public TownsController(IServiceTown serviceTown)
		{
			_serviceTown = serviceTown;
		}


		[HttpGet("Towns/CreateTown")]
		public async Task <IActionResult> CreateTown()
		{
			var countriesList = await _serviceTown.GetCountries();
			ViewBag.TotalCountries = countriesList;
			TownDto townDto = new TownDto();
			return PartialView("_TownModelPartial", townDto);
		}

		[HttpPost("Towns/CreateTown")]
		public async Task<IActionResult> CreateTown(TownDto townDto)
		{
			if (!ModelState.IsValid)
			{
				return PartialView("_TownModelPartial", townDto);
			}
			else { 
				try
				{
					await _serviceTown.CreateTown(townDto);
					return RedirectToAction("Index");
				}
				catch (Exception ex)
				{
					return PartialView("_TownModelPartial", townDto);
				}
			}
		}

		[HttpGet("Towns/Index")]
		public async Task <IActionResult> Index()
		{
			try
			{
				var data = await _serviceTown.GetTowns();
				var townList = await _serviceTown.TownCount();
				ViewBag.TotalTowns = townList;
				return View(data);
			}

			catch (Exception ex)
			{
				return BadRequest(ex);
			}
		}

		[HttpPost("Towns/DeleteTown")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteTown(int? id)
		{
			try
			{
				if (id != null)
				{
					await _serviceTown.DeleteTown(id);
				}
				return RedirectToAction("Index");
			}
			catch (Exception ex)
			{
				return BadRequest(ex);
			}
		}

		[HttpGet("Towns/EditTown/{id}")]
		public async Task<IActionResult> EditTown(int id)
		{
			var countriesList = await _serviceTown.GetCountries();
			ViewBag.TotalCountries = countriesList;
			var townDto = await _serviceTown.GetTown(id);
			return PartialView("_EditTownModelPartial", townDto);
		}

		[HttpPost("Towns/EditTown")]
		public async Task<IActionResult> EditTown(TownDto townDto)
		{
			if (!ModelState.IsValid)
			{
				//ModelState.AddModelError("", "");
				return View(townDto);
			}
			else
			{
				try
				{
					await _serviceTown.EditTown(townDto);
					return RedirectToAction("Index");
				}
				catch (Exception ex)
				{
					return BadRequest(ex);
				}
			}
		}
	}
}

Koios/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Koios/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Koios</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Towns" asp-action="Index">Koios</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Koios/Views/Towns/Index.cshtml
@model IEnumerable<Koios.Models.TownDto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="float-left">
    Town Count: @ViewBag.TotalTowns
</div>
<button type="button" class="btn btn-primary float-right mb-4 mt-2" data-toggle="ajax-modal" data-target="#addTown"
        data-url="@Url.ActionLink("CreateTown", "Towns")">
    Add Town
</button>
<div id="PlaceHolderHere"></div>
<table class="table">
    <thead>
        <tr>
            <th>
                Town Name
            </th>
            <th>
                Postal Code
            </th>
            <th>
                Country
            </th>
            <th>
                Edit
            </th>
            <th>
                Delete
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TownName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PostalCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Countries.CountryName)
                </td>
                <td>
                    <button type="button" class="btn btn-info" data-toggle="ajax-modal" data-target="#addTown"
                            data-url="@Url.Action("EditTown", "Towns", new { id = item.TownId })">
                        Edit
                    </button>
                </td>
                <td>
                    @using (Html.BeginForm("DeleteTown", "Towns", new { id = item.TownId }, FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(modelItem => item.TownId)
                            <button type="submit" class="btn btn-danger" value="Delete" data-toggle="modal" onclick="return confirm('Are you sure you want to delete this Town?')" data-target="#confirm-delete">Delete</button>
                        }
                </td>
            </tr>
        }
    </tbody>
</table>

Koios/Views/Towns/_EditTownModelPartial.cshtml
@model TownDto
<div class="modal fade" id="addTown">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="addTownLabel">Edit Town</h4>
                <button type="button" class="close" data-dismiss="modal">
                    <span>x</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="EditTown">
                    <div class="form-group">
                        <label class="text-danger">Field with * is required</label>
                        <input type="hidden" asp-for="@Model.TownId" />
                    </div>
                    <div class="form-group">
                        <label>Country</label><label class="text-danger"> *</label>
                        @Html.DropDownListFor(Model => Model.CountryId, new SelectList(ViewBag.TotalCountries, "CountryId", "CountryName"), new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Town Name</label><label class="text-danger"> *</label>
                        <input id="TownName" asp-for="TownName" placeholder="Zagreb" class="form-control" required/>
                        <span id="nonUnique" style="margin-top:5px !important;" class="alert-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Postal Code</label><label class="text-danger"> *</label>
                        <input asp-for="PostalCode" placeholder="10000" class="form-control" required />
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" data-save="modal">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Koios/Views/Towns/_TownModelPartial.cshtml
@model TownDto
<div class="modal fade" id="addTown">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="addTownLabel">Add Town</h4>
                <button type="button" class="close" data-dismiss="modal">
                    <span>x</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="CreateTown" method="post">
                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()"/>
                    <div class="form-group">
                        <label class="text-danger">Field with * is required</label>
                    </div>
                    <div class="form-group">
                        <label>Country</label><label class="text-danger"> *</label>
                        @Html.DropDownListFor(Model => Model.CountryId, new SelectList(ViewBag.TotalCountries, "CountryId", "CountryName"), new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Town Name</label><label class="text-danger"> *</label>
                        <input asp-for="TownName" placeholder="Zagreb" class="form-control" required />
                        <span id="nonUnique" style="margin-top:5px !important;" class="alert-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Postal Code</label><label class="text-danger"> *</label>
                        <input asp-for="PostalCode" placeholder="10000" class="form-control" required />
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" data-save="modal">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>